//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/WCF")]
    [System.SerializableAttribute()]
    public partial class Empleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((this.CedulaField.Equals(value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cargo {
            get {
                return this.cargoField;
            }
            set {
                if ((object.ReferenceEquals(this.cargoField, value) != true)) {
                    this.cargoField = value;
                    this.RaisePropertyChanged("cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceDatos")]
    public interface IServiceDatos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDatos/GetEmpleadoByID", ReplyAction="http://tempuri.org/IServiceDatos/GetEmpleadoByIDResponse")]
        Web.ServiceReference1.Empleado GetEmpleadoByID(int Cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDatos/GetEmpleadoByID", ReplyAction="http://tempuri.org/IServiceDatos/GetEmpleadoByIDResponse")]
        System.Threading.Tasks.Task<Web.ServiceReference1.Empleado> GetEmpleadoByIDAsync(int Cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDatos/GetEmpleadosByCargo", ReplyAction="http://tempuri.org/IServiceDatos/GetEmpleadosByCargoResponse")]
        Web.ServiceReference1.Empleado[] GetEmpleadosByCargo(string IDCargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDatos/GetEmpleadosByCargo", ReplyAction="http://tempuri.org/IServiceDatos/GetEmpleadosByCargoResponse")]
        System.Threading.Tasks.Task<Web.ServiceReference1.Empleado[]> GetEmpleadosByCargoAsync(string IDCargo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDatosChannel : Web.ServiceReference1.IServiceDatos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDatosClient : System.ServiceModel.ClientBase<Web.ServiceReference1.IServiceDatos>, Web.ServiceReference1.IServiceDatos {
        
        public ServiceDatosClient() {
        }
        
        public ServiceDatosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDatosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDatosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDatosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Web.ServiceReference1.Empleado GetEmpleadoByID(int Cedula) {
            return base.Channel.GetEmpleadoByID(Cedula);
        }
        
        public System.Threading.Tasks.Task<Web.ServiceReference1.Empleado> GetEmpleadoByIDAsync(int Cedula) {
            return base.Channel.GetEmpleadoByIDAsync(Cedula);
        }
        
        public Web.ServiceReference1.Empleado[] GetEmpleadosByCargo(string IDCargo) {
            return base.Channel.GetEmpleadosByCargo(IDCargo);
        }
        
        public System.Threading.Tasks.Task<Web.ServiceReference1.Empleado[]> GetEmpleadosByCargoAsync(string IDCargo) {
            return base.Channel.GetEmpleadosByCargoAsync(IDCargo);
        }
    }
}
